---
jobs:
  include:
    - &test
      stage: test
      language: python
      python: "2.7"
      cache: pip
      dist: xenial
      sudo: required
      install:
        - .travis/setup.sh
      script:
        # the python venv needs to be in the path for molecule to run
        # https://unix.stackexchange.com/questions/83191/how-to-make-sudo-preserve-path
        - sudo env "PATH=$PATH" molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
