---
language: node_js
node_js:
  - v10
  - v8
jobs:
  include:
    - stage: Code coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
